armor
auto-key-retrieve
cert-digest-algo SHA512
default-preference-list SHA512 SHA384 SHA256 AES256 AES192 AES ZLIB BZIP2 ZIP Uncompressed
keyid-format 0xlong
no-emit-version
no-greeting
personal-cipher-preferences AES256 AES192 AES
personal-digest-preferences SHA512 SHA384 SHA256
pinentry-mode loopback
require-cross-certification
with-fingerprint
