#!/bin/bash
# vim:set foldmethod=marker:

# pretty print with testdox - red is failed, green is passed. Phpunit, why
# don't you already do this?
#
# This also uses utf-8 checkmarks and X marks, aligns the titles a little
# differently, adds a vertical space, etc.

# unofficial bash strict mode {{{
# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
# IFS=$'\n\t'
# }}}

# colors {{{
BLACK="$(tput setaf 0)"
RED="$(tput setaf 1)"
GREEN="$(tput setaf 2)"
YELLOW="$(tput setaf 3)"
BLUE="$(tput setaf 4)"
PINK="$(tput setaf 5)"
CYAN="$(tput setaf 6)"
WHITE="$(tput setaf 7)"
NORMAL="$(tput sgr0)"
# }}}

# example output:
#
#   SomeNamespace\SomeClass (<-- this line is white)
#
# ✘ gets canonical url with no search data (<-- this line is red)
# ✔ gets canonical url with search data (<-- checked lines are green)
#
php \
    -dmemory_limit=2048M \
    -ddisplay_errors=on \
    ./vendor/bin/phpunit \
    --testdox \
    --verbose \
    $@ | while read -r LINE; do
    echo -E $LINE |
        sed -E -e 's/^[a-zA-Z0-9\\_]+$/   & \
            /' |
        sed -E -e "s/^(\[x\]) (It )?(.*)$/ ${GREEN}✔ \3${NORMAL}/" |
        sed -E -e "s/^(\[ \]) (It )?(.*)$/ ${RED}✘ \3${NORMAL}/"
done
