-- https://stackoverflow.com/questions/313359/annoying-vim-unindent-rules
-- https://github.com/nvim-treesitter/nvim-treesitter/issues/462#issuecomment-700278736
-- vim.bo.indentexpr = nil
-- vim.bo.autoindent = true
-- vim.bo.smartindent = true
-- vim.bo.cindent = true
-- vim.bo.cinwords = table.concat({
--   'if',
--   'else',
--   'elseif',
--   'do',
--   'while',
--   'foreach',
--   'for',
--   'case',
--   'default',
--   'function',
--   'class',
--   'interface',
--   'abstract',
--   'private',
--   'public',
--   'protected',
--   'final',
-- }, ',')
